/**
 * Always-on tests (CI included): a synthetic operation generated by tools/planner-oracle/export_synthetic.py.
 * 1. Parity: the TypeScript engine reproduces the Python oracle's synthetic plans exactly.
 * 2. Optimizer guarantees on the same plans (and on the real dataset days when the golden files exist).
 */
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { weight } from "../src/eligibility";
import { optimizePlan } from "../src/optimize";
import { planDay } from "../src/plan";
import { createReference, makeOrder, type Reference, type ReferenceInput } from "../src/reference";
import { checkVehicleDay } from "../src/vehicle-day";
import type { Order, Plan } from "../src/types";
import { PLAN_NAMES, goldenPlan, hasGolden, reference as realReference, type GoldenPlan } from "./fixtures";

const here = dirname(fileURLToPath(import.meta.url));
const DIR = resolve(here, "synthetic");
const SYNTH = ["synth-peak-2b", "synth-peak-live", "synth-north-workshop"] as const;
const load = <T,>(f: string) => JSON.parse(readFileSync(join(DIR, f), "utf8")) as T;
const R: Reference = createReference(load<ReferenceInput>("reference.json"));
const synth = (name: string) => load<GoldenPlan>(`plan-${name}.json`);

const refsOf = (p: Plan) => Object.fromEntries([...p.trips].map(([v, ts]) => [v, ts.map((t) => t.map((o) => o.ref))]));

describe("parity with the Python oracle (synthetic operation)", () => {
  for (const name of SYNTH) {
    it(`reproduces ${name}`, () => {
      const g = synth(name);
      const plan = planDay(R, g.orders.map((o) => makeOrder(R, o)), g.status, g.ctx, g.mode, g.fuelUsed);
      expect(refsOf(plan)).toEqual(g.plan.trips);
      expect(Object.fromEntries([...plan.deferrals].map(([r, d]) => [r, { kind: d.kind, reason: d.reason, lostTo: d.lostTo }]))).toEqual(g.plan.deferrals);
      expect(plan.timed.map((t) => [t.vehicleId, t.number, t.stops.map((o) => o.ref), t.tripMinutes])).toEqual(
        g.plan.timed.map((t) => [t.vehicleId, t.number, t.stops, t.tripMinutes]),
      );
      plan.timed.forEach((t, i) => {
        expect(t.departure ?? 0).toBeCloseTo(g.plan.timed[i]!.departure ?? 0, 9);
        t.planned.forEach((leg, k) => expect(leg.arrive).toBeCloseTo(g.plan.timed[i]!.planned[k]!.arrive, 9));
      });
    });
  }

  it("the peak day really exceeds capacity (deferrals appear)", () => {
    for (const name of SYNTH) expect(Object.keys(synth(name).plan.deferrals).length).toBeGreaterThan(0);
  });
});

function checkGuarantees(R: Reference, g: GoldenPlan) {
  const orders: Order[] = g.orders.map((o) => makeOrder(R, o));
  const base = planDay(R, orders, g.status, g.ctx, g.mode, g.fuelUsed);
  const { plan, stats } = optimizePlan(R, orders, g.status, g.ctx, g.mode, g.fuelUsed, base);

  // 1. nothing the baseline served is dropped, nothing is served twice
  const servedBase = new Set([...base.trips.values()].flat(2).map((o) => o.ref));
  const servedNow = [...plan.trips.values()].flat(2).map((o) => o.ref);
  expect(new Set(servedNow).size).toBe(servedNow.length);
  for (const ref of servedBase) expect(servedNow).toContain(ref);

  // 2. lexicographic improvement: more priority weight, or the same weight in no more trips
  expect(stats.servedWeight).toBeGreaterThanOrEqual(stats.baseWeight - 1e-9);
  if (Math.abs(stats.servedWeight - stats.baseWeight) < 1e-9) expect(stats.trips).toBeLessThanOrEqual(stats.baseTrips);

  // 3. every vehicle-day satisfies the full rule set
  for (const [v, day] of plan.trips) expect(checkVehicleDay(R, v, day, g.ctx, g.mode, g.fuelUsed[v] ?? 0).ok, `${v} breaks a rule`).toBe(true);

  // 4. deferrals list exactly the orders still not served; timed trips match the trips
  const all = new Set(orders.map((o) => o.ref));
  const deferred = [...all].filter((r) => !servedNow.includes(r));
  expect([...plan.deferrals.keys()].sort()).toEqual(deferred.sort());
  expect(plan.timed.reduce((n, t) => n + t.stops.length, 0)).toBe(servedNow.length);

  // 5. deterministic
  const again = optimizePlan(R, orders, g.status, g.ctx, g.mode, g.fuelUsed, planDay(R, orders, g.status, g.ctx, g.mode, g.fuelUsed));
  expect(refsOf(again.plan)).toEqual(refsOf(plan));

  const gain = orders.filter((o) => !servedBase.has(o.ref) && servedNow.includes(o.ref));
  return { stats, gain: gain.reduce((n, o) => n + weight(o), 0) };
}

describe("optimizer guarantees (synthetic operation)", () => {
  for (const name of SYNTH) it(`improves ${name} without breaking a rule`, () => checkGuarantees(R, synth(name)));

  it("serves at least one extra order or saves a trip somewhere in the synthetic peak days", () => {
    const results = SYNTH.map((n) => checkGuarantees(R, synth(n)).stats);
    expect(results.some((s) => s.served > s.baseServed || s.trips < s.baseTrips)).toBe(true);
  });
});

describe.skipIf(!hasGolden)("optimizer guarantees (real dataset days)", () => {
  for (const name of PLAN_NAMES) it(`improves ${name} without breaking a rule`, () => checkGuarantees(realReference(), goldenPlan(name)));
});
